/***** Generated by BuildGen S.c header generator *****/
#ifndef _DATA_SCRIPTS_BUILDGEN_BUILDGEN_EXE_INFO_H
#define _DATA_SCRIPTS_BUILDGEN_BUILDGEN_EXE_INFO_H

extern const char *DEFAULT_GENERATOR;
extern const char *LUALIBS_ROOT;
extern const char *VERSION;

#endif /* _DATA_SCRIPTS_BUILDGEN_BUILDGEN_EXE_INFO_H */
