language: cpp
compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get install cmake lua50 luarocks gtest
 - luarocks install penlight
script:
 - SRC="$(pwd)"
 - echo $SRC
 - mkdir "$SRC/cmake/" && cd "$SRC/cmake/" && cmake .. && make install
 - mkdir "$SRC/bs/"    && cd "$SRC/bg/"    && gen -Ddebug -Dtest .. && make test
after-script:
 -  bg/buildgen-exe/test
