language: cpp
compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get install cmake lua50 luarocks libgtest-dev
 - sudo luarocks install luafilesystem
 - sudo luarocks install penlight
script:
 - SRC="$(pwd)"
 - OLDPATH=$PATH
 - mkdir "$SRC/cmake/" && cd "$SRC/cmake/" && cmake "-DCMAKE_INSTALL_PREFIX:PATH=$SRC/cmakeins/" .. && make install
 - PATH="$SRC/cmakeins/bin/:$OLDPATH"
 - mkdir "$SRC/bg/"    && cd "$SRC/bg/"    && gen -Ddebug -Dtest "-Dprefix=$SRC/bgins/" .. && make test
 - PATH="$SRC/bgins/bin/:$OLDPATH"
 - rm -rv "$SRC/bg/"*
 - mkdir "$SRC/bg/"    && cd "$SRC/bg/"    && gen -Ddebug -Dtest "-Dprefix=$SRC/bgins/" .. && make test
after-script:
 -  bg/buildgen-exe/test
