language: cpp
compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get install cmake lua50 luarocks libgtest-dev
 - sudo luarocks install luafilesystem
 - sudo luarocks install penlight
 - src="$(pwd)"
 - mkdir "$src/gtest/" && cd "$src/gtest/" && cmake /usr/src/gtest/ && make && sudo cp libgtest.a libgtest_main.a /usr/lib/
 - cd "$src"
script:
 - SRC="$(pwd)"
 - OLDPATH=$PATH
 - mkdir "$src/cmake/" && cd "$src/cmake/" && cmake "-DCMAKE_INSTALL_PREFIX:PATH=$SRC/cmakeins/" .. && make install
 - PATH="$src/cmakeins/bin/:$OLDPATH"
 - mkdir "$src/bg0/"    && cd "$src/bg0/"  && sudo gen -Ddebug -Dtest "-Dprefix=$SRC/bgins0/" .. && make install
 - PATH="$src/bgins0/bin/:$OLDPATH"
 - mkdir "$src/bg1/"    && cd "$src/bg1/"  && sudo gen -Ddebug -Dtest "-Dprefix=$SRC/bgins1/" .. && make test

 - echo "######################$src"
 - cd "$src/"
 - bg1/buildgen-exe/test
