language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install cmake
script:
 - SRC="$(pwd)"
 - echo $SRC
 - mkdir "$SRC/cmake/" && "$SRC/cmake/" && cmake .. && make install
 - mkdir "$SRC/bs/"    && "$SRC/bg/"    && gen -Ddebug -Dtest .. && make test
after-script:
 -  bg/buildgen-exe/test
